### ISSUE TITLE
Manage nested IF statements

### ISSUE THREAD

**Issue by ritacionfoli** [lubosdz/yii2-template-engine#3]
Hi, is there a way to manage nested if statements?

**Comment by lubosdz** [comment]
Can you give an example of what you want to accomplish?
Nested `ifs` are not supported due to parsing complexity.

**Comment by ritacionfoli** [comment]
I've a for cicle and within it there are some if statements like this:

{{ for item in items }}
  {{ if condition 1 }}
     html code
     {{ if subcondition1 }}

     {{ elseif subcondition 2 }}

     {{ endif }}
  {{ elseif condition2 }}

  {{ elseif ..... }}

  {{ endif }}
{{ endfor }}

The code is interpreted correctly up to the first subcondition; afterwards, it also prints the placeholders with the subsequent if statements.

**Comment by lubosdz** [comment]
Yeah, that won't work. You have to denormalize / combine conditions like so:

~~~php
{{ for item in items }}

   {{ if condition 1 and condition 2 and subcondition 1 and subcondition 2 }}
      html code 1212
   {{  elseif condition 1 and condition 2 and subcondition 1 }}
      html code 121
   {{  elseif condition 1 and condition 2 }}
      html code 12
   {{  elseif condition 1 }}
      html code 1
   {{ endif }}

{{ endfor }}
~~~

Or you can optimize / group conditions, if possible:

~~~php
{{ for item in items }}

   {{ SET cond = condition 1 && condition 2  }}
   {{ SET subcond = subcondition 1 && subcondition 2  }}

   {{ if cond and subcond }}
      html code 1212
   {{  elseif cond and subcondition 1 }}
      html code 121
   {{  elseif condition 1 and condition 2 }}
      html code 12
   {{  elseif condition 1 }}
      html code 1
   {{ endif }}

{{ endfor }}

~~~


It's a bit more complex, increases code boilerplate, but is doable.
You can use any number of combined conditions since engine [applies](https://github.com/lubosdz/yii2-template-engine/blob/main/src/TemplateEngine.php#L543) `eval` on whole IF statement. See also [test](https://github.com/lubosdz/yii2-template-engine/blob/main/tests/TemplateEngineTest.php#L263).
Parsing would be a nightmare at costs of performace and error proneability.
As far as I recall, neither [Twig](https://twig.symfony.com/doc/3.x/tags/if.html) supports nested `ifs`.
But [Blade](https://laracasts.com/discuss/channels/general-discussion/nested-if-statements) seems to support it, because of different parsing approach. If you really need complex solution you may need to use alternate templating engine.

**Comment by ritacionfoli** [comment]
I have already developed a similar solution; thank you for your response.

**Comment by ritacionfoli** [comment]
I have already developed a similar solution; thank you for your response.
